# Generated by Django 5.0.4 on 2024-06-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_name',
        ),
    ]
