# Generated by Django 5.0.4 on 2024-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
