# Generated by Django 5.0.4 on 2024-05-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0002_product_discount_product_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_amount',
            new_name='discount_price',
        ),
    ]
