# Generated by Django 5.0.4 on 2024-06-15 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0009_remove_product_image_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='colour',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.product'),
        ),
    ]
