# Generated by Django 5.0.4 on 2024-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0010_remove_productimage_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='product_images/image-not-found-icon.svg', null=True, upload_to='product_images/'),
        ),
    ]
